stages:
- name: Install & Build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm install -g npm-cli-login && npm set registry https://npm.demandcluster.com && npm-cli-login --quotes && yarn && yarn build && yarn postbuild && npm-cli-login --quotes && yarn publish:release
    env:
      HOME: .
      NPM_EMAIL: devops@demandcluster.com
      NPM_REGISTRY: https://npm.demandcluster.com
      NPM_USER: demandcluster
    envFrom:
    - sourceName: cicd
      sourceKey: NPM_PASS
      targetKey: NPM_PASS
timeout: 60
notification: {}
